# Generated by Django 5.0.6 on 2024-05-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancereview', '0002_remove_employee_id_alter_employee_employeeid'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/employee/'),
        ),
    ]
