# Generated by Django 5.0.6 on 2024-05-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancereview', '0003_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(upload_to='uploads/employee/'),
        ),
    ]
