# Generated by Django 5.0.6 on 2024-05-20 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancereview', '0005_remove_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(default='', upload_to='uploads/employee/'),
        ),
    ]
