# Generated by Django 5.0.6 on 2024-05-20 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancereview', '0006_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='hireDate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employeeName', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=50)),
                ('dateOfReview', models.CharField(max_length=30)),
                ('timeOfReview', models.CharField(max_length=30)),
                ('jobKnowledge', models.CharField(max_length=30)),
                ('workQuality', models.CharField(max_length=30)),
                ('initiative', models.CharField(max_length=30)),
                ('communication', models.CharField(max_length=30)),
                ('dependability', models.CharField(max_length=30)),
                ('employeeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='performancereview.employee')),
            ],
        ),
    ]
