# Generated by Django 5.0.6 on 2024-05-21 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancereview', '0008_branch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='branch',
            options={'verbose_name_plural': 'Branches'},
        ),
        migrations.AddField(
            model_name='performancereview',
            name='overallFeedback',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
