# Generated by Django 5.0.6 on 2024-05-21 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performancereview', '0010_alter_performancereview_dateofreview_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performancereview',
            name='communication',
            field=models.CharField(choices=[('5-Excellent', '5-Excellent'), ('4-Exceeds Expectations', '4-Exceeds Expectations'), ('3-Meets Expectations', '3-Meets Expectations'), ('2-Needs Improvement', '2-Needs Improvement'), ('1-Unacceptable', '1-Unacceptable')], max_length=30),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='dependability',
            field=models.CharField(choices=[('5-Excellent', '5-Excellent'), ('4-Exceeds Expectations', '4-Exceeds Expectations'), ('3-Meets Expectations', '3-Meets Expectations'), ('2-Needs Improvement', '2-Needs Improvement'), ('1-Unacceptable', '1-Unacceptable')], max_length=30),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='initiative',
            field=models.CharField(choices=[('5-Excellent', '5-Excellent'), ('4-Exceeds Expectations', '4-Exceeds Expectations'), ('3-Meets Expectations', '3-Meets Expectations'), ('2-Needs Improvement', '2-Needs Improvement'), ('1-Unacceptable', '1-Unacceptable')], max_length=30),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='jobKnowledge',
            field=models.CharField(choices=[('5-Excellent', '5-Excellent'), ('4-Exceeds Expectations', '4-Exceeds Expectations'), ('3-Meets Expectations', '3-Meets Expectations'), ('2-Needs Improvement', '2-Needs Improvement'), ('1-Unacceptable', '1-Unacceptable')], max_length=30),
        ),
        migrations.AlterField(
            model_name='performancereview',
            name='workQuality',
            field=models.CharField(choices=[('5-Excellent', '5-Excellent'), ('4-Exceeds Expectations', '4-Exceeds Expectations'), ('3-Meets Expectations', '3-Meets Expectations'), ('2-Needs Improvement', '2-Needs Improvement'), ('1-Unacceptable', '1-Unacceptable')], max_length=30),
        ),
    ]
