# Generated by Django 5.0.6 on 2024-05-23 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performancereview', '0012_employee_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
