# Generated by Django 5.0.6 on 2024-05-23 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('performancereview', '0015_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='password',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
    ]
